PALETTE_WHITE = (255, 255, 255)
PALETTE_BLACK = (0, 0, 0)
PALETTE_RED = (0, 0, 255)
PALETTE_GREEN = (0, 255, 0)
PALETTE_DARK_GREEN = (0, 200, 0)
PALETTE_BLUE = (255, 0, 0)
PALETTE_CYAN = (255, 255, 0)
PALETTE_YELLOW = (0, 255, 255) 

PALETTE_GRAY_DARK = (50, 50, 50)
PALETTE_GRAY_MEDIUM = (80, 80, 80)
PALETTE_GRAY_PLACEHOLDER = (100, 100, 100)
PALETTE_GRAY_LIGHT = (200, 200, 200)

# --- Colores de la Interfaz ---
UI_KEY_WHITE_ACTIVE = PALETTE_GREEN
UI_KEY_WHITE_INACTIVE = PALETTE_GRAY_LIGHT
UI_KEY_WHITE_BORDER = PALETTE_BLACK
UI_KEY_WHITE_TEXT = PALETTE_BLACK

UI_KEY_BLACK_ACTIVE = PALETTE_DARK_GREEN
UI_KEY_BLACK_INACTIVE = PALETTE_GRAY_DARK
UI_KEY_BLACK_BORDER = PALETTE_WHITE

UI_NOTE_HIT = PALETTE_GREEN
UI_NOTE_FALLING = PALETTE_BLUE
UI_HIT_LINE = PALETTE_RED
UI_SCORE_TEXT = PALETTE_DARK_GREEN

UI_BTN_BG_OVERLAY = 255
UI_BTN_BORDER = PALETTE_BLACK
UI_BTN_TEXT = PALETTE_BLACK

UI_MENU_HEADER_BG = PALETTE_GRAY_DARK
UI_MENU_HEADER_TEXT = PALETTE_WHITE
UI_MENU_OPT_BG = PALETTE_GRAY_MEDIUM
UI_MENU_OPT_BORDER = PALETTE_WHITE
UI_MENU_OPT_TEXT = PALETTE_GRAY_LIGHT

UI_ICON_PLACEHOLDER_BG = PALETTE_YELLOW
UI_ICON_BG_EMPTY = PALETTE_GRAY_PLACEHOLDER
UI_ICON_BORDER_DEFAULT = PALETTE_WHITE
UI_ICON_BORDER_SELECTED = PALETTE_GREEN
UI_ICON_BORDER_UNSELECTED = PALETTE_GRAY_LIGHT

UI_FINGER_DOT_FILL = PALETTE_RED
UI_FINGER_DOT_BORDER = PALETTE_WHITE
